1

In [ ]:
import numpy as np

def result_mark(weights: np.array, marks: np.array) -> int:
  weighted_sum = np.dot(weights, marks)
  return int(round(weighted_sum))

weights = np.array([0.3, 0.4, 0.2, 0.1])
marks = np.array([7, 10, 8, 6])

res = result_mark(weights, marks)
print(res)

оценка за курс = 8


2

In [ ]:
import numpy as np

def change_array(array, number):
    array[::3] = number
    return array

array = np.array([3, 5, 1, 0, -3, 22, 213436])
number = -111

res = change_array(array, number)
print(res)


[-111    5    1 -111   -3   22 -111]


3

In [ ]:
import numpy as np

def find_close(array1, array2, precision):
    abs_diff = np.abs(array1 - array2)
    close_indices = np.where(abs_diff <= precision)[0]
    return close_indices

array1 = np.array([1.5, 0.5, 2, -4.1, -3, 6, -1])
array2 = np.array([1.2, 0.5, 1, -4.0, 3, 0, -1.2])
precision = 0.5

res = find_close(array1, array2, precision)
print(res)

[0 1 3 6]


4

In [ ]:
import numpy as np

def block_matrix(block):
    top_row = np.hstack((block, block))
    bottom_row = np.hstack((block, block))
    return np.vstack((top_row, bottom_row))

block = np.array([[0, 1, 2], [3, 4, 5]])

res = block_matrix(block)
print(res)


[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


5

In [ ]:
import numpy as np

def diag_prod(matrix):
    diag_elements = matrix.diagonal()
    non_zero_diag_elements = diag_elements[diag_elements != 0]
    result = np.prod(non_zero_diag_elements)
    return result

matrix = np.array([[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]])

res = diag_prod(matrix)
print(res)



32


6

In [ ]:
import numpy as np

def normalize(matrix: np.array) -> np.array:
    means = np.mean(matrix, axis=0)
    stds = np.std(matrix, axis=0)
    stds[stds == 0] = 1
    normal_matrix = (matrix - means) / stds
    return normal_matrix

matrix = np.array([[-7, 2, 42], [2, 10, 50], [5, 4, 10]])
normal_matrix = normalize(matrix)
print(normal_matrix)


[[-1.37281295 -0.98058068  0.46291005]
 [ 0.39223227  1.37281295  0.9258201 ]
 [ 0.98058068 -0.39223227 -1.38873015]]


8

In [ ]:
import numpy as np

def make_symmetric(matrix: np.array) -> np.array:
    return matrix + matrix.T - np.diag(matrix.diagonal())

matrix = np.array([[1, 2, 3, 4], [0, 5, 6, 7], [0, 0, 8, 9], [0, 0, 0, 10]])
res = make_symmetric(matrix)
print(res)


[[ 1  2  3  4]
 [ 2  5  6  7]
 [ 3  6  8  9]
 [ 4  7  9 10]]


9

In [ ]:
import numpy as np

def construct_matrix(m: int, a:int, b: int) -> np.array:
    row = np.arange(a, b + 1)
    result = np.tile(row, (m, 1))
    return result

m = 3
a = 2
b = 6
res = construct_matrix(m, a, b)
print(res)


[[2 3 4 5 6]
 [2 3 4 5 6]
 [2 3 4 5 6]]


10

In [ ]:
import numpy as np

def cosine_similarity(vec1: np.array, vec2: np.array) -> float:
    dot_product = np.dot(vec1, vec2)
    norm_vec1 = np.linalg.norm(vec1)
    norm_vec2 = np.linalg.norm(vec2)
    similarity = dot_product / (norm_vec1 * norm_vec2)
    return similarity

vec1 = np.array([-2, 1, 0, -5, 4, 3, -3])
vec2 = np.array([0, 2, -2, 10, 6, 0, 0])
res = cosine_similarity(vec1, vec2)
print(res)


-0.25
